/*
 *  IBM Confidential OCO Source Materials
 *                                                                 
 *  5725-I43 Copyright IBM Corp. 2011, 2017
 *                                                                   
 *  The source code for this program is not published or otherwise
 *  divested of its trade secrets, irrespective of what has
 *  been deposited with the U.S. Copyright Office.
 *                   
 */


/*
 * OpenWhisk REST API
 * API for OpenWhisk
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ibm.mfp.adapters.sample.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.ibm.mfp.adapters.sample.model.EntityBrief;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;

/*
 *  IBM Confidential OCO Source Materials
 *                                                                 
 *  5725-I43 Copyright IBM Corp. 2011, 2017
 *                                                                   
 *  The source code for this program is not published or otherwise
 *  divested of its trade secrets, irrespective of what has
 *  been deposited with the U.S. Copyright Office.
 *                   
 */


/**
 * InlineResponse200
 */
@javax.annotation.Generated(value = "com.github.mfpdev.adapters.swagger.codegen.MfpAdapterCodegen", date = "2017-07-03T19:13:35.134+05:30")
public class InlineResponse200   {
  @JsonProperty("actions")
  private List<EntityBrief> actions = new ArrayList<EntityBrief>();

  @JsonProperty("triggers")
  private List<EntityBrief> triggers = new ArrayList<EntityBrief>();

  @JsonProperty("rules")
  private List<EntityBrief> rules = new ArrayList<EntityBrief>();

  @JsonProperty("packages")
  private List<EntityBrief> packages = new ArrayList<EntityBrief>();

  public InlineResponse200 actions(List<EntityBrief> actions) {
    this.actions = actions;
    return this;
  }

  public InlineResponse200 addActionsItem(EntityBrief actionsItem) {
    this.actions.add(actionsItem);
    return this;
  }

   /**
   * Get actions
   * @return actions
  **/
  @JsonProperty("actions")
  @ApiModelProperty(required = true, value = "")
  @NotNull
  public List<EntityBrief> getActions() {
    return actions;
  }

  public void setActions(List<EntityBrief> actions) {
    this.actions = actions;
  }

  public InlineResponse200 triggers(List<EntityBrief> triggers) {
    this.triggers = triggers;
    return this;
  }

  public InlineResponse200 addTriggersItem(EntityBrief triggersItem) {
    this.triggers.add(triggersItem);
    return this;
  }

   /**
   * Get triggers
   * @return triggers
  **/
  @JsonProperty("triggers")
  @ApiModelProperty(required = true, value = "")
  @NotNull
  public List<EntityBrief> getTriggers() {
    return triggers;
  }

  public void setTriggers(List<EntityBrief> triggers) {
    this.triggers = triggers;
  }

  public InlineResponse200 rules(List<EntityBrief> rules) {
    this.rules = rules;
    return this;
  }

  public InlineResponse200 addRulesItem(EntityBrief rulesItem) {
    this.rules.add(rulesItem);
    return this;
  }

   /**
   * Get rules
   * @return rules
  **/
  @JsonProperty("rules")
  @ApiModelProperty(required = true, value = "")
  @NotNull
  public List<EntityBrief> getRules() {
    return rules;
  }

  public void setRules(List<EntityBrief> rules) {
    this.rules = rules;
  }

  public InlineResponse200 packages(List<EntityBrief> packages) {
    this.packages = packages;
    return this;
  }

  public InlineResponse200 addPackagesItem(EntityBrief packagesItem) {
    this.packages.add(packagesItem);
    return this;
  }

   /**
   * Get packages
   * @return packages
  **/
  @JsonProperty("packages")
  @ApiModelProperty(required = true, value = "")
  @NotNull
  public List<EntityBrief> getPackages() {
    return packages;
  }

  public void setPackages(List<EntityBrief> packages) {
    this.packages = packages;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200 inlineResponse200 = (InlineResponse200) o;
    return Objects.equals(this.actions, inlineResponse200.actions) &&
        Objects.equals(this.triggers, inlineResponse200.triggers) &&
        Objects.equals(this.rules, inlineResponse200.rules) &&
        Objects.equals(this.packages, inlineResponse200.packages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actions, triggers, rules, packages);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200 {\n");
    
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("    triggers: ").append(toIndentedString(triggers)).append("\n");
    sb.append("    rules: ").append(toIndentedString(rules)).append("\n");
    sb.append("    packages: ").append(toIndentedString(packages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

