/*
 * Conversation
 * The IBM Watson&trade; Conversation service combines machine learning, natural language understanding, and integrated dialog tools to create conversation flows between your apps and your users.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ibm.mfp.adapters.sample.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.validation.constraints.*;

/**
 * BaseWorkspace
 */
@javax.annotation.Generated(value = "com.github.mfpdev.adapters.swagger.codegen.MfpAdapterCodegen", date = "2017-05-19T13:34:31.991+05:30")
public class BaseWorkspace   {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("language")
  private String language = null;

  public BaseWorkspace name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the workspace.
   * @return name
  **/
  @JsonProperty("name")
  @ApiModelProperty(value = "The name of the workspace.")

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public BaseWorkspace description(String description) {
    this.description = description;
    return this;
  }

   /**
   * The description of the workspace.
   * @return description
  **/
  @JsonProperty("description")
  @ApiModelProperty(value = "The description of the workspace.")

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public BaseWorkspace language(String language) {
    this.language = language;
    return this;
  }

   /**
   * The language of the workspace.
   * @return language
  **/
  @JsonProperty("language")
  @ApiModelProperty(value = "The language of the workspace.")

  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BaseWorkspace baseWorkspace = (BaseWorkspace) o;
    return Objects.equals(this.name, baseWorkspace.name) &&
        Objects.equals(this.description, baseWorkspace.description) &&
        Objects.equals(this.language, baseWorkspace.language);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, language);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BaseWorkspace {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
