/*
 * Conversation
 * The IBM Watson&trade; Conversation service combines machine learning, natural language understanding, and integrated dialog tools to create conversation flows between your apps and your users.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ibm.mfp.adapters.sample.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.ibm.mfp.adapters.sample.model.CreateValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;

/**
 * CreateEntity
 */
@javax.annotation.Generated(value = "com.github.mfpdev.adapters.swagger.codegen.MfpAdapterCodegen", date = "2017-05-19T13:34:31.991+05:30")
public class CreateEntity   {
  @JsonProperty("entity")
  private String entity = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("metadata")
  private Object metadata = null;

  @JsonProperty("values")
  private List<CreateValue> values = null;

  @JsonProperty("fuzzy_match")
  private Boolean fuzzyMatch = null;

  public CreateEntity entity(String entity) {
    this.entity = entity;
    return this;
  }

   /**
   * The name of the entity.
   * @return entity
  **/
  @JsonProperty("entity")
  @ApiModelProperty(required = true, value = "The name of the entity.")
  @NotNull 

  public String getEntity() {
    return entity;
  }

  public void setEntity(String entity) {
    this.entity = entity;
  }

  public CreateEntity description(String description) {
    this.description = description;
    return this;
  }

   /**
   * The description of the entity.
   * @return description
  **/
  @JsonProperty("description")
  @ApiModelProperty(value = "The description of the entity.")

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CreateEntity metadata(Object metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Any metadata related to the value.
   * @return metadata
  **/
  @JsonProperty("metadata")
  @ApiModelProperty(value = "Any metadata related to the value.")

  public Object getMetadata() {
    return metadata;
  }

  public void setMetadata(Object metadata) {
    this.metadata = metadata;
  }

  public CreateEntity values(List<CreateValue> values) {
    this.values = values;
    return this;
  }

  public CreateEntity addValuesItem(CreateValue valuesItem) {
    if (this.values == null) {
      this.values = new ArrayList<CreateValue>();
    }
    this.values.add(valuesItem);
    return this;
  }

   /**
   * An array of entity values.
   * @return values
  **/
  @JsonProperty("values")
  @ApiModelProperty(value = "An array of entity values.")

  public List<CreateValue> getValues() {
    return values;
  }

  public void setValues(List<CreateValue> values) {
    this.values = values;
  }

  public CreateEntity fuzzyMatch(Boolean fuzzyMatch) {
    this.fuzzyMatch = fuzzyMatch;
    return this;
  }

   /**
   * Whether to use fuzzy matching for the entity.
   * @return fuzzyMatch
  **/
  @JsonProperty("fuzzy_match")
  @ApiModelProperty(value = "Whether to use fuzzy matching for the entity.")

  public Boolean getFuzzyMatch() {
    return fuzzyMatch;
  }

  public void setFuzzyMatch(Boolean fuzzyMatch) {
    this.fuzzyMatch = fuzzyMatch;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateEntity createEntity = (CreateEntity) o;
    return Objects.equals(this.entity, createEntity.entity) &&
        Objects.equals(this.description, createEntity.description) &&
        Objects.equals(this.metadata, createEntity.metadata) &&
        Objects.equals(this.values, createEntity.values) &&
        Objects.equals(this.fuzzyMatch, createEntity.fuzzyMatch);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entity, description, metadata, values, fuzzyMatch);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateEntity {\n");
    
    sb.append("    entity: ").append(toIndentedString(entity)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("    fuzzyMatch: ").append(toIndentedString(fuzzyMatch)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
