/*
 * Conversation
 * The IBM Watson&trade; Conversation service combines machine learning, natural language understanding, and integrated dialog tools to create conversation flows between your apps and your users.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ibm.mfp.adapters.sample.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.ibm.mfp.adapters.sample.model.EntityResponse;
import com.ibm.mfp.adapters.sample.model.ValueCollection;
import com.ibm.mfp.adapters.sample.model.ValueExportResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;
import javax.validation.constraints.*;

/**
 * EntityExportResponse
 */
@javax.annotation.Generated(value = "com.github.mfpdev.adapters.swagger.codegen.MfpAdapterCodegen", date = "2017-05-19T13:34:31.991+05:30")
public class EntityExportResponse   {
  @JsonProperty("entity")
  private String entity = null;

  @JsonProperty("created")
  private DateTime created = null;

  @JsonProperty("updated")
  private DateTime updated = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("metadata")
  private Object metadata = null;

  @JsonProperty("fuzzy_match")
  private Boolean fuzzyMatch = null;

  @JsonProperty("values")
  private List<ValueExportResponse> values = null;

  public EntityExportResponse entity(String entity) {
    this.entity = entity;
    return this;
  }

   /**
   * The name of the entity.
   * @return entity
  **/
  @JsonProperty("entity")
  @ApiModelProperty(required = true, value = "The name of the entity.")
  @NotNull 

  public String getEntity() {
    return entity;
  }

  public void setEntity(String entity) {
    this.entity = entity;
  }

  public EntityExportResponse created(DateTime created) {
    this.created = created;
    return this;
  }

   /**
   * The timestamp for creation of the entity.
   * @return created
  **/
  @JsonProperty("created")
  @ApiModelProperty(required = true, value = "The timestamp for creation of the entity.")
  @NotNull 

  public DateTime getCreated() {
    return created;
  }

  public void setCreated(DateTime created) {
    this.created = created;
  }

  public EntityExportResponse updated(DateTime updated) {
    this.updated = updated;
    return this;
  }

   /**
   * The timestamp for the last update to the entity.
   * @return updated
  **/
  @JsonProperty("updated")
  @ApiModelProperty(required = true, value = "The timestamp for the last update to the entity.")
  @NotNull 

  public DateTime getUpdated() {
    return updated;
  }

  public void setUpdated(DateTime updated) {
    this.updated = updated;
  }

  public EntityExportResponse description(String description) {
    this.description = description;
    return this;
  }

   /**
   * The description of the entity.
   * @return description
  **/
  @JsonProperty("description")
  @ApiModelProperty(value = "The description of the entity.")

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public EntityExportResponse metadata(Object metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Any metadata related to the entity.
   * @return metadata
  **/
  @JsonProperty("metadata")
  @ApiModelProperty(value = "Any metadata related to the entity.")

  public Object getMetadata() {
    return metadata;
  }

  public void setMetadata(Object metadata) {
    this.metadata = metadata;
  }

  public EntityExportResponse fuzzyMatch(Boolean fuzzyMatch) {
    this.fuzzyMatch = fuzzyMatch;
    return this;
  }

   /**
   * Whether fuzzy matching is used for the entity.
   * @return fuzzyMatch
  **/
  @JsonProperty("fuzzy_match")
  @ApiModelProperty(value = "Whether fuzzy matching is used for the entity.")

  public Boolean getFuzzyMatch() {
    return fuzzyMatch;
  }

  public void setFuzzyMatch(Boolean fuzzyMatch) {
    this.fuzzyMatch = fuzzyMatch;
  }

  public EntityExportResponse values(List<ValueExportResponse> values) {
    this.values = values;
    return this;
  }

  public EntityExportResponse addValuesItem(ValueExportResponse valuesItem) {
    if (this.values == null) {
      this.values = new ArrayList<ValueExportResponse>();
    }
    this.values.add(valuesItem);
    return this;
  }

   /**
   * An array of entity values.
   * @return values
  **/
  @JsonProperty("values")
  @ApiModelProperty(value = "An array of entity values.")

  public List<ValueExportResponse> getValues() {
    return values;
  }

  public void setValues(List<ValueExportResponse> values) {
    this.values = values;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntityExportResponse entityExportResponse = (EntityExportResponse) o;
    return Objects.equals(this.entity, entityExportResponse.entity) &&
        Objects.equals(this.created, entityExportResponse.created) &&
        Objects.equals(this.updated, entityExportResponse.updated) &&
        Objects.equals(this.description, entityExportResponse.description) &&
        Objects.equals(this.metadata, entityExportResponse.metadata) &&
        Objects.equals(this.fuzzyMatch, entityExportResponse.fuzzyMatch) &&
        Objects.equals(this.values, entityExportResponse.values);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entity, created, updated, description, metadata, fuzzyMatch, values);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntityExportResponse {\n");
    
    sb.append("    entity: ").append(toIndentedString(entity)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    fuzzyMatch: ").append(toIndentedString(fuzzyMatch)).append("\n");
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
