/*
 * Conversation
 * The IBM Watson&trade; Conversation service combines machine learning, natural language understanding, and integrated dialog tools to create conversation flows between your apps and your users.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ibm.mfp.adapters.sample.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.ibm.mfp.adapters.sample.model.IntentExportResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;

/**
 * IntentCollection
 */
@javax.annotation.Generated(value = "com.github.mfpdev.adapters.swagger.codegen.MfpAdapterCodegen", date = "2017-05-19T13:34:31.991+05:30")
public class IntentCollection   {
  @JsonProperty("intents")
  private List<IntentExportResponse> intents = null;

  public IntentCollection intents(List<IntentExportResponse> intents) {
    this.intents = intents;
    return this;
  }

  public IntentCollection addIntentsItem(IntentExportResponse intentsItem) {
    if (this.intents == null) {
      this.intents = new ArrayList<IntentExportResponse>();
    }
    this.intents.add(intentsItem);
    return this;
  }

   /**
   * An array of intents.
   * @return intents
  **/
  @JsonProperty("intents")
  @ApiModelProperty(value = "An array of intents.")

  public List<IntentExportResponse> getIntents() {
    return intents;
  }

  public void setIntents(List<IntentExportResponse> intents) {
    this.intents = intents;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IntentCollection intentCollection = (IntentCollection) o;
    return Objects.equals(this.intents, intentCollection.intents);
  }

  @Override
  public int hashCode() {
    return Objects.hash(intents);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IntentCollection {\n");
    
    sb.append("    intents: ").append(toIndentedString(intents)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
