/*
 *  IBM Confidential OCO Source Materials
 *                                                                 
 *  5725-I43 Copyright IBM Corp. 2011, 2017
 *                                                                   
 *  The source code for this program is not published or otherwise
 *  divested of its trade secrets, irrespective of what has
 *  been deposited with the U.S. Copyright Office.
 *                   
 */


/*
 * Conversation
 * The IBM Watson&trade; Conversation service combines machine learning, natural language understanding, and integrated dialog tools to create conversation flows between your apps and your users.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ibm.mfp.adapters.sample.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.validation.constraints.*;

/*
 *  IBM Confidential OCO Source Materials
 *                                                                 
 *  5725-I43 Copyright IBM Corp. 2011, 2017
 *                                                                   
 *  The source code for this program is not published or otherwise
 *  divested of its trade secrets, irrespective of what has
 *  been deposited with the U.S. Copyright Office.
 *                   
 */


/**
 * The pagination data for the returned objects.
 */
@ApiModel(description = "The pagination data for the returned objects.")
@javax.annotation.Generated(value = "com.github.mfpdev.adapters.swagger.codegen.MfpAdapterCodegen", date = "2017-06-21T18:01:40.287+05:30")
public class PaginationResponse   {
  @JsonProperty("refresh_url")
  private String refreshUrl = null;

  @JsonProperty("next_url")
  private String nextUrl = null;

  @JsonProperty("total")
  private Integer total = null;

  @JsonProperty("matched")
  private Integer matched = null;

  public PaginationResponse refreshUrl(String refreshUrl) {
    this.refreshUrl = refreshUrl;
    return this;
  }

   /**
   * The URL that will return the same page of results.
   * @return refreshUrl
  **/
  @JsonProperty("refresh_url")
  @ApiModelProperty(required = true, value = "The URL that will return the same page of results.")
  @NotNull
  public String getRefreshUrl() {
    return refreshUrl;
  }

  public void setRefreshUrl(String refreshUrl) {
    this.refreshUrl = refreshUrl;
  }

  public PaginationResponse nextUrl(String nextUrl) {
    this.nextUrl = nextUrl;
    return this;
  }

   /**
   * The URL that will return the next page of results.
   * @return nextUrl
  **/
  @JsonProperty("next_url")
  @ApiModelProperty(value = "The URL that will return the next page of results.")
  public String getNextUrl() {
    return nextUrl;
  }

  public void setNextUrl(String nextUrl) {
    this.nextUrl = nextUrl;
  }

  public PaginationResponse total(Integer total) {
    this.total = total;
    return this;
  }

   /**
   * Reserved for future use.
   * @return total
  **/
  @JsonProperty("total")
  @ApiModelProperty(value = "Reserved for future use.")
  public Integer getTotal() {
    return total;
  }

  public void setTotal(Integer total) {
    this.total = total;
  }

  public PaginationResponse matched(Integer matched) {
    this.matched = matched;
    return this;
  }

   /**
   * Reserved for future use.
   * @return matched
  **/
  @JsonProperty("matched")
  @ApiModelProperty(value = "Reserved for future use.")
  public Integer getMatched() {
    return matched;
  }

  public void setMatched(Integer matched) {
    this.matched = matched;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaginationResponse paginationResponse = (PaginationResponse) o;
    return Objects.equals(this.refreshUrl, paginationResponse.refreshUrl) &&
        Objects.equals(this.nextUrl, paginationResponse.nextUrl) &&
        Objects.equals(this.total, paginationResponse.total) &&
        Objects.equals(this.matched, paginationResponse.matched);
  }

  @Override
  public int hashCode() {
    return Objects.hash(refreshUrl, nextUrl, total, matched);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaginationResponse {\n");
    
    sb.append("    refreshUrl: ").append(toIndentedString(refreshUrl)).append("\n");
    sb.append("    nextUrl: ").append(toIndentedString(nextUrl)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    matched: ").append(toIndentedString(matched)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

