/*
 *  IBM Confidential OCO Source Materials
 *                                                                 
 *  5725-I43 Copyright IBM Corp. 2011, 2017
 *                                                                   
 *  The source code for this program is not published or otherwise
 *  divested of its trade secrets, irrespective of what has
 *  been deposited with the U.S. Copyright Office.
 *                   
 */


/*
 * Conversation
 * The IBM Watson&trade; Conversation service combines machine learning, natural language understanding, and integrated dialog tools to create conversation flows between your apps and your users.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ibm.mfp.adapters.sample.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.ibm.mfp.adapters.sample.model.RuntimeLogMessage;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;

/*
 *  IBM Confidential OCO Source Materials
 *                                                                 
 *  5725-I43 Copyright IBM Corp. 2011, 2017
 *                                                                   
 *  The source code for this program is not published or otherwise
 *  divested of its trade secrets, irrespective of what has
 *  been deposited with the U.S. Copyright Office.
 *                   
 */


/**
 * RuntimeOutput
 */
@javax.annotation.Generated(value = "com.github.mfpdev.adapters.swagger.codegen.MfpAdapterCodegen", date = "2017-06-21T18:01:40.287+05:30")
public class RuntimeOutput   {
  @JsonProperty("text")
  private List<String> text = null;

  @JsonProperty("log_messages")
  private List<RuntimeLogMessage> logMessages = null;

  @JsonProperty("nodes_visited")
  private List<String> nodesVisited = null;

  public RuntimeOutput text(List<String> text) {
    this.text = text;
    return this;
  }

  public RuntimeOutput addTextItem(String textItem) {
    if (this.text == null) {
      this.text = new ArrayList<String>();
    }
    this.text.add(textItem);
    return this;
  }

   /**
   * An array of responses to the user.
   * @return text
  **/
  @JsonProperty("text")
  @ApiModelProperty(value = "An array of responses to the user.")
  public List<String> getText() {
    return text;
  }

  public void setText(List<String> text) {
    this.text = text;
  }

  public RuntimeOutput logMessages(List<RuntimeLogMessage> logMessages) {
    this.logMessages = logMessages;
    return this;
  }

  public RuntimeOutput addLogMessagesItem(RuntimeLogMessage logMessagesItem) {
    if (this.logMessages == null) {
      this.logMessages = new ArrayList<RuntimeLogMessage>();
    }
    this.logMessages.add(logMessagesItem);
    return this;
  }

   /**
   * Up to 50 messages logged with the request
   * @return logMessages
  **/
  @JsonProperty("log_messages")
  @ApiModelProperty(value = "Up to 50 messages logged with the request")
  public List<RuntimeLogMessage> getLogMessages() {
    return logMessages;
  }

  public void setLogMessages(List<RuntimeLogMessage> logMessages) {
    this.logMessages = logMessages;
  }

  public RuntimeOutput nodesVisited(List<String> nodesVisited) {
    this.nodesVisited = nodesVisited;
    return this;
  }

  public RuntimeOutput addNodesVisitedItem(String nodesVisitedItem) {
    if (this.nodesVisited == null) {
      this.nodesVisited = new ArrayList<String>();
    }
    this.nodesVisited.add(nodesVisitedItem);
    return this;
  }

   /**
   * An array of the nodes that were triggered to create the response.
   * @return nodesVisited
  **/
  @JsonProperty("nodes_visited")
  @ApiModelProperty(value = "An array of the nodes that were triggered to create the response.")
  public List<String> getNodesVisited() {
    return nodesVisited;
  }

  public void setNodesVisited(List<String> nodesVisited) {
    this.nodesVisited = nodesVisited;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RuntimeOutput runtimeOutput = (RuntimeOutput) o;
    return Objects.equals(this.text, runtimeOutput.text) &&
        Objects.equals(this.logMessages, runtimeOutput.logMessages) &&
        Objects.equals(this.nodesVisited, runtimeOutput.nodesVisited);
  }

  @Override
  public int hashCode() {
    return Objects.hash(text, logMessages, nodesVisited);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RuntimeOutput {\n");
    
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    logMessages: ").append(toIndentedString(logMessages)).append("\n");
    sb.append("    nodesVisited: ").append(toIndentedString(nodesVisited)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

