/*
 * Conversation
 * The IBM Watson&trade; Conversation service combines machine learning, natural language understanding, and integrated dialog tools to create conversation flows between your apps and your users.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ibm.mfp.adapters.sample.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.validation.constraints.*;

/**
 * RuntimeLogMessage
 */
@javax.annotation.Generated(value = "com.github.mfpdev.adapters.swagger.codegen.MfpAdapterCodegen", date = "2017-05-19T13:34:31.991+05:30")
public class RuntimeLogMessage   {
  @JsonProperty("level")
  private String level = null;

  @JsonProperty("msg")
  private String msg = null;

  public RuntimeLogMessage level(String level) {
    this.level = level;
    return this;
  }

   /**
   * The severity of the message (info, error, or warn).
   * @return level
  **/
  @JsonProperty("level")
  @ApiModelProperty(required = true, value = "The severity of the message (info, error, or warn).")
  @NotNull 

  public String getLevel() {
    return level;
  }

  public void setLevel(String level) {
    this.level = level;
  }

  public RuntimeLogMessage msg(String msg) {
    this.msg = msg;
    return this;
  }

   /**
   * The text of the message.
   * @return msg
  **/
  @JsonProperty("msg")
  @ApiModelProperty(required = true, value = "The text of the message.")
  @NotNull 

  public String getMsg() {
    return msg;
  }

  public void setMsg(String msg) {
    this.msg = msg;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RuntimeLogMessage runtimeLogMessage = (RuntimeLogMessage) o;
    return Objects.equals(this.level, runtimeLogMessage.level) &&
        Objects.equals(this.msg, runtimeLogMessage.msg);
  }

  @Override
  public int hashCode() {
    return Objects.hash(level, msg);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RuntimeLogMessage {\n");
    
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("    msg: ").append(toIndentedString(msg)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
