/*
 * Conversation
 * The IBM Watson&trade; Conversation service combines machine learning, natural language understanding, and integrated dialog tools to create conversation flows between your apps and your users.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ibm.mfp.adapters.sample.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.ibm.mfp.adapters.sample.model.PaginationResponse;
import com.ibm.mfp.adapters.sample.model.WorkspaceResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;

/**
 * WorkspaceCollectionResponse
 */
@javax.annotation.Generated(value = "com.github.mfpdev.adapters.swagger.codegen.MfpAdapterCodegen", date = "2017-05-19T13:34:31.991+05:30")
public class WorkspaceCollectionResponse   {
  @JsonProperty("workspaces")
  private List<WorkspaceResponse> workspaces = new ArrayList<WorkspaceResponse>();

  @JsonProperty("pagination")
  private PaginationResponse pagination = null;

  public WorkspaceCollectionResponse workspaces(List<WorkspaceResponse> workspaces) {
    this.workspaces = workspaces;
    return this;
  }

  public WorkspaceCollectionResponse addWorkspacesItem(WorkspaceResponse workspacesItem) {
    this.workspaces.add(workspacesItem);
    return this;
  }

   /**
   * An array of workspaces.
   * @return workspaces
  **/
  @JsonProperty("workspaces")
  @ApiModelProperty(required = true, value = "An array of workspaces.")
  @NotNull 

  public List<WorkspaceResponse> getWorkspaces() {
    return workspaces;
  }

  public void setWorkspaces(List<WorkspaceResponse> workspaces) {
    this.workspaces = workspaces;
  }

  public WorkspaceCollectionResponse pagination(PaginationResponse pagination) {
    this.pagination = pagination;
    return this;
  }

   /**
   * Get pagination
   * @return pagination
  **/
  @JsonProperty("pagination")
  @ApiModelProperty(required = true, value = "")
  @NotNull 

  public PaginationResponse getPagination() {
    return pagination;
  }

  public void setPagination(PaginationResponse pagination) {
    this.pagination = pagination;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkspaceCollectionResponse workspaceCollectionResponse = (WorkspaceCollectionResponse) o;
    return Objects.equals(this.workspaces, workspaceCollectionResponse.workspaces) &&
        Objects.equals(this.pagination, workspaceCollectionResponse.pagination);
  }

  @Override
  public int hashCode() {
    return Objects.hash(workspaces, pagination);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkspaceCollectionResponse {\n");
    
    sb.append("    workspaces: ").append(toIndentedString(workspaces)).append("\n");
    sb.append("    pagination: ").append(toIndentedString(pagination)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
