/*
 * Discovery
 * The IBM Watson&trade; Discovery Service is a cognitive search and content analytics engine that you can add to applications to identify patterns, trends and actionable insights to drive better decision-making. Securely unify structured and unstructured data with pre-enriched content, and use a simplified query language to eliminate the need for manual filtering of results. 
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ibm.mfp.adapters.sample.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.ibm.mfp.adapters.sample.model.QueryAggregation;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;

/**
 * AggregationResult
 */
@javax.annotation.Generated(value = "com.github.mfpdev.adapters.swagger.codegen.MfpAdapterCodegen", date = "2017-05-15T10:26:38.328+05:30")
public class AggregationResult   {
  @JsonProperty("key")
  private String key = null;

  @JsonProperty("matching_results")
  private Integer matchingResults = null;

  @JsonProperty("aggregations")
  private List<QueryAggregation> aggregations = null;

  public AggregationResult key(String key) {
    this.key = key;
    return this;
  }

   /**
   * Key that matched the aggregation type.
   * @return key
  **/
  @JsonProperty("key")
  @ApiModelProperty(value = "Key that matched the aggregation type.")

  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }

  public AggregationResult matchingResults(Integer matchingResults) {
    this.matchingResults = matchingResults;
    return this;
  }

   /**
   * Number of matching results.
   * @return matchingResults
  **/
  @JsonProperty("matching_results")
  @ApiModelProperty(value = "Number of matching results.")

  public Integer getMatchingResults() {
    return matchingResults;
  }

  public void setMatchingResults(Integer matchingResults) {
    this.matchingResults = matchingResults;
  }

  public AggregationResult aggregations(List<QueryAggregation> aggregations) {
    this.aggregations = aggregations;
    return this;
  }

  public AggregationResult addAggregationsItem(QueryAggregation aggregationsItem) {
    if (this.aggregations == null) {
      this.aggregations = new ArrayList<QueryAggregation>();
    }
    this.aggregations.add(aggregationsItem);
    return this;
  }

   /**
   * Aggregations returned in the case of chained aggregations.
   * @return aggregations
  **/
  @JsonProperty("aggregations")
  @ApiModelProperty(value = "Aggregations returned in the case of chained aggregations.")

  public List<QueryAggregation> getAggregations() {
    return aggregations;
  }

  public void setAggregations(List<QueryAggregation> aggregations) {
    this.aggregations = aggregations;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AggregationResult aggregationResult = (AggregationResult) o;
    return Objects.equals(this.key, aggregationResult.key) &&
        Objects.equals(this.matchingResults, aggregationResult.matchingResults) &&
        Objects.equals(this.aggregations, aggregationResult.aggregations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, matchingResults, aggregations);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AggregationResult {\n");
    
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    matchingResults: ").append(toIndentedString(matchingResults)).append("\n");
    sb.append("    aggregations: ").append(toIndentedString(aggregations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
