/*
 * Discovery
 * The IBM Watson&trade; Discovery Service is a cognitive search and content analytics engine that you can add to applications to identify patterns, trends and actionable insights to drive better decision-making. Securely unify structured and unstructured data with pre-enriched content, and use a simplified query language to eliminate the need for manual filtering of results. 
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ibm.mfp.adapters.sample.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.ibm.mfp.adapters.sample.model.Notice;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;
import javax.validation.constraints.*;

/**
 * Status information about a submitted document
 */
@ApiModel(description = "Status information about a submitted document")
@javax.annotation.Generated(value = "com.github.mfpdev.adapters.swagger.codegen.MfpAdapterCodegen", date = "2017-05-15T10:26:38.328+05:30")
public class DocumentStatus   {
  @JsonProperty("document_id")
  private String documentId = null;

  @JsonProperty("configuration_id")
  private String configurationId = null;

  @JsonProperty("created")
  private DateTime created = null;

  @JsonProperty("updated")
  private DateTime updated = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("status_description")
  private String statusDescription = null;

  @JsonProperty("notices")
  private List<Notice> notices = null;

  public DocumentStatus documentId(String documentId) {
    this.documentId = documentId;
    return this;
  }

   /**
   * The unique identifier of the document
   * @return documentId
  **/
  @JsonProperty("document_id")
  @ApiModelProperty(value = "The unique identifier of the document")

  public String getDocumentId() {
    return documentId;
  }

  public void setDocumentId(String documentId) {
    this.documentId = documentId;
  }

  public DocumentStatus configurationId(String configurationId) {
    this.configurationId = configurationId;
    return this;
  }

   /**
   * Get configurationId
   * @return configurationId
  **/
  @JsonProperty("configuration_id")
  @ApiModelProperty(value = "")

  public String getConfigurationId() {
    return configurationId;
  }

  public void setConfigurationId(String configurationId) {
    this.configurationId = configurationId;
  }

  public DocumentStatus created(DateTime created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @JsonProperty("created")
  @ApiModelProperty(value = "")

  public DateTime getCreated() {
    return created;
  }

  public void setCreated(DateTime created) {
    this.created = created;
  }

  public DocumentStatus updated(DateTime updated) {
    this.updated = updated;
    return this;
  }

   /**
   * Get updated
   * @return updated
  **/
  @JsonProperty("updated")
  @ApiModelProperty(value = "")

  public DateTime getUpdated() {
    return updated;
  }

  public void setUpdated(DateTime updated) {
    this.updated = updated;
  }

  public DocumentStatus status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Status of the document in the ingestion process
   * @return status
  **/
  @JsonProperty("status")
  @ApiModelProperty(value = "Status of the document in the ingestion process")

  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public DocumentStatus statusDescription(String statusDescription) {
    this.statusDescription = statusDescription;
    return this;
  }

   /**
   * Description of the document status
   * @return statusDescription
  **/
  @JsonProperty("status_description")
  @ApiModelProperty(value = "Description of the document status")

  public String getStatusDescription() {
    return statusDescription;
  }

  public void setStatusDescription(String statusDescription) {
    this.statusDescription = statusDescription;
  }

  public DocumentStatus notices(List<Notice> notices) {
    this.notices = notices;
    return this;
  }

  public DocumentStatus addNoticesItem(Notice noticesItem) {
    if (this.notices == null) {
      this.notices = new ArrayList<Notice>();
    }
    this.notices.add(noticesItem);
    return this;
  }

   /**
   * Array of notices produced by the document-ingestion process
   * @return notices
  **/
  @JsonProperty("notices")
  @ApiModelProperty(value = "Array of notices produced by the document-ingestion process")

  public List<Notice> getNotices() {
    return notices;
  }

  public void setNotices(List<Notice> notices) {
    this.notices = notices;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocumentStatus documentStatus = (DocumentStatus) o;
    return Objects.equals(this.documentId, documentStatus.documentId) &&
        Objects.equals(this.configurationId, documentStatus.configurationId) &&
        Objects.equals(this.created, documentStatus.created) &&
        Objects.equals(this.updated, documentStatus.updated) &&
        Objects.equals(this.status, documentStatus.status) &&
        Objects.equals(this.statusDescription, documentStatus.statusDescription) &&
        Objects.equals(this.notices, documentStatus.notices);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documentId, configurationId, created, updated, status, statusDescription, notices);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocumentStatus {\n");
    
    sb.append("    documentId: ").append(toIndentedString(documentId)).append("\n");
    sb.append("    configurationId: ").append(toIndentedString(configurationId)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    statusDescription: ").append(toIndentedString(statusDescription)).append("\n");
    sb.append("    notices: ").append(toIndentedString(notices)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
