/*
 *  IBM Confidential OCO Source Materials
 *                                                                 
 *  5725-I43 Copyright IBM Corp. 2011, 2017
 *                                                                   
 *  The source code for this program is not published or otherwise
 *  divested of its trade secrets, irrespective of what has
 *  been deposited with the U.S. Copyright Office.
 *                   
 */


/*
 * Discovery
 * The IBM Watson&trade; Discovery Service is a cognitive search and content analytics engine that you can add to applications to identify patterns, trends and actionable insights to drive better decision-making. Securely unify structured and unstructured data with pre-enriched content, and use a simplified query language to eliminate the need for manual filtering of results. 
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ibm.mfp.adapters.sample.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ibm.mfp.adapters.sample.model.IndexCapacity;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;
import javax.validation.constraints.*;

/*
 *  IBM Confidential OCO Source Materials
 *                                                                 
 *  5725-I43 Copyright IBM Corp. 2011, 2017
 *                                                                   
 *  The source code for this program is not published or otherwise
 *  divested of its trade secrets, irrespective of what has
 *  been deposited with the U.S. Copyright Office.
 *                   
 */


/**
 * Details about an environment
 */
@ApiModel(description = "Details about an environment")
@javax.annotation.Generated(value = "com.github.mfpdev.adapters.swagger.codegen.MfpAdapterCodegen", date = "2017-06-21T18:39:34.122+05:30")
public class Environment   {
  @JsonProperty("environment_id")
  private String environmentId = null;

  @JsonProperty("name")
  private String name = "";

  @JsonProperty("description")
  private String description = "";

  @JsonProperty("created")
  private DateTime created = null;

  @JsonProperty("updated")
  private DateTime updated = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("read_only")
  private Boolean readOnly = null;

/*
 *  IBM Confidential OCO Source Materials
 *                                                                 
 *  5725-I43 Copyright IBM Corp. 2011, 2017
 *                                                                   
 *  The source code for this program is not published or otherwise
 *  divested of its trade secrets, irrespective of what has
 *  been deposited with the U.S. Copyright Office.
 *                   
 */


/**
   * Size of the environment
   */
  public enum SizeEnum {
    _0("0"),
    
    _1("1"),
    
    _2("2"),
    
    _3("3");

    private String value;

    SizeEnum(String value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static SizeEnum fromValue(String text) {
      for (SizeEnum b : SizeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("size")
  private SizeEnum size = SizeEnum._1;

  @JsonProperty("index_capacity")
  private IndexCapacity indexCapacity = null;

   /**
   * Unique identifier for this environment
   * @return environmentId
  **/
  @JsonProperty("environment_id")
  @ApiModelProperty(value = "Unique identifier for this environment")
  public String getEnvironmentId() {
    return environmentId;
  }

  public Environment name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name that identifies this environment
   * @return name
  **/
  @JsonProperty("name")
  @ApiModelProperty(value = "Name that identifies this environment")
 @Size(min=0,max=255)  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Environment description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description of the environment
   * @return description
  **/
  @JsonProperty("description")
  @ApiModelProperty(value = "Description of the environment")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

   /**
   * Creation date of the environment, in the format yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
   * @return created
  **/
  @JsonProperty("created")
  @ApiModelProperty(value = "Creation date of the environment, in the format yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")
  public DateTime getCreated() {
    return created;
  }

   /**
   * Date of most recent environment update, in the format yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
   * @return updated
  **/
  @JsonProperty("updated")
  @ApiModelProperty(value = "Date of most recent environment update, in the format yyyy-MM-dd'T'HH:mm:ss.SSS'Z'")
  public DateTime getUpdated() {
    return updated;
  }

   /**
   * Status of the environment
   * @return status
  **/
  @JsonProperty("status")
  @ApiModelProperty(value = "Status of the environment")
  public String getStatus() {
    return status;
  }

   /**
   * If true, then the environment contains read-only collections which are maintained by IBM.
   * @return readOnly
  **/
  @JsonProperty("read_only")
  @ApiModelProperty(value = "If true, then the environment contains read-only collections which are maintained by IBM.")
  public Boolean getReadOnly() {
    return readOnly;
  }

  public Environment size(SizeEnum size) {
    this.size = size;
    return this;
  }

   /**
   * Size of the environment
   * @return size
  **/
  @JsonProperty("size")
  @ApiModelProperty(value = "Size of the environment")
  public SizeEnum getSize() {
    return size;
  }

  public void setSize(SizeEnum size) {
    this.size = size;
  }

  public Environment indexCapacity(IndexCapacity indexCapacity) {
    this.indexCapacity = indexCapacity;
    return this;
  }

   /**
   * Object containing information about disk and memory usage
   * @return indexCapacity
  **/
  @JsonProperty("index_capacity")
  @ApiModelProperty(value = "Object containing information about disk and memory usage")
  public IndexCapacity getIndexCapacity() {
    return indexCapacity;
  }

  public void setIndexCapacity(IndexCapacity indexCapacity) {
    this.indexCapacity = indexCapacity;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Environment environment = (Environment) o;
    return Objects.equals(this.environmentId, environment.environmentId) &&
        Objects.equals(this.name, environment.name) &&
        Objects.equals(this.description, environment.description) &&
        Objects.equals(this.created, environment.created) &&
        Objects.equals(this.updated, environment.updated) &&
        Objects.equals(this.status, environment.status) &&
        Objects.equals(this.readOnly, environment.readOnly) &&
        Objects.equals(this.size, environment.size) &&
        Objects.equals(this.indexCapacity, environment.indexCapacity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(environmentId, name, description, created, updated, status, readOnly, size, indexCapacity);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Environment {\n");
    
    sb.append("    environmentId: ").append(toIndentedString(environmentId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    readOnly: ").append(toIndentedString(readOnly)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    indexCapacity: ").append(toIndentedString(indexCapacity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

