/*
 *  IBM Confidential OCO Source Materials
 *                                                                 
 *  5725-I43 Copyright IBM Corp. 2011, 2017
 *                                                                   
 *  The source code for this program is not published or otherwise
 *  divested of its trade secrets, irrespective of what has
 *  been deposited with the U.S. Copyright Office.
 *                   
 */


/*
 * Discovery
 * The IBM Watson&trade; Discovery Service is a cognitive search and content analytics engine that you can add to applications to identify patterns, trends and actionable insights to drive better decision-making. Securely unify structured and unstructured data with pre-enriched content, and use a simplified query language to eliminate the need for manual filtering of results. 
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ibm.mfp.adapters.sample.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.ibm.mfp.adapters.sample.model.XPathPatterns;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import javax.validation.constraints.*;

/*
 *  IBM Confidential OCO Source Materials
 *                                                                 
 *  5725-I43 Copyright IBM Corp. 2011, 2017
 *                                                                   
 *  The source code for this program is not published or otherwise
 *  divested of its trade secrets, irrespective of what has
 *  been deposited with the U.S. Copyright Office.
 *                   
 */


/**
 * A list of HTML conversion settings
 */
@ApiModel(description = "A list of HTML conversion settings")
@javax.annotation.Generated(value = "com.github.mfpdev.adapters.swagger.codegen.MfpAdapterCodegen", date = "2017-06-21T18:39:34.122+05:30")
public class HtmlSettings   {
  @JsonProperty("exclude_tags_completely")
  private List<String> excludeTagsCompletely = null;

  @JsonProperty("exclude_tags_keep_content")
  private List<String> excludeTagsKeepContent = null;

  @JsonProperty("keep_content")
  private XPathPatterns keepContent = null;

  @JsonProperty("exclude_content")
  private XPathPatterns excludeContent = null;

  @JsonProperty("keep_tag_attributes")
  private List<String> keepTagAttributes = null;

  @JsonProperty("exclude_tag_attributes")
  private List<String> excludeTagAttributes = null;

  public HtmlSettings excludeTagsCompletely(List<String> excludeTagsCompletely) {
    this.excludeTagsCompletely = excludeTagsCompletely;
    return this;
  }

  public HtmlSettings addExcludeTagsCompletelyItem(String excludeTagsCompletelyItem) {
    if (this.excludeTagsCompletely == null) {
      this.excludeTagsCompletely = new ArrayList<String>();
    }
    this.excludeTagsCompletely.add(excludeTagsCompletelyItem);
    return this;
  }

   /**
   * Get excludeTagsCompletely
   * @return excludeTagsCompletely
  **/
  @JsonProperty("exclude_tags_completely")
  @ApiModelProperty(value = "")
  public List<String> getExcludeTagsCompletely() {
    return excludeTagsCompletely;
  }

  public void setExcludeTagsCompletely(List<String> excludeTagsCompletely) {
    this.excludeTagsCompletely = excludeTagsCompletely;
  }

  public HtmlSettings excludeTagsKeepContent(List<String> excludeTagsKeepContent) {
    this.excludeTagsKeepContent = excludeTagsKeepContent;
    return this;
  }

  public HtmlSettings addExcludeTagsKeepContentItem(String excludeTagsKeepContentItem) {
    if (this.excludeTagsKeepContent == null) {
      this.excludeTagsKeepContent = new ArrayList<String>();
    }
    this.excludeTagsKeepContent.add(excludeTagsKeepContentItem);
    return this;
  }

   /**
   * Get excludeTagsKeepContent
   * @return excludeTagsKeepContent
  **/
  @JsonProperty("exclude_tags_keep_content")
  @ApiModelProperty(value = "")
  public List<String> getExcludeTagsKeepContent() {
    return excludeTagsKeepContent;
  }

  public void setExcludeTagsKeepContent(List<String> excludeTagsKeepContent) {
    this.excludeTagsKeepContent = excludeTagsKeepContent;
  }

  public HtmlSettings keepContent(XPathPatterns keepContent) {
    this.keepContent = keepContent;
    return this;
  }

   /**
   * Get keepContent
   * @return keepContent
  **/
  @JsonProperty("keep_content")
  @ApiModelProperty(value = "")
  public XPathPatterns getKeepContent() {
    return keepContent;
  }

  public void setKeepContent(XPathPatterns keepContent) {
    this.keepContent = keepContent;
  }

  public HtmlSettings excludeContent(XPathPatterns excludeContent) {
    this.excludeContent = excludeContent;
    return this;
  }

   /**
   * Get excludeContent
   * @return excludeContent
  **/
  @JsonProperty("exclude_content")
  @ApiModelProperty(value = "")
  public XPathPatterns getExcludeContent() {
    return excludeContent;
  }

  public void setExcludeContent(XPathPatterns excludeContent) {
    this.excludeContent = excludeContent;
  }

  public HtmlSettings keepTagAttributes(List<String> keepTagAttributes) {
    this.keepTagAttributes = keepTagAttributes;
    return this;
  }

  public HtmlSettings addKeepTagAttributesItem(String keepTagAttributesItem) {
    if (this.keepTagAttributes == null) {
      this.keepTagAttributes = new ArrayList<String>();
    }
    this.keepTagAttributes.add(keepTagAttributesItem);
    return this;
  }

   /**
   * Get keepTagAttributes
   * @return keepTagAttributes
  **/
  @JsonProperty("keep_tag_attributes")
  @ApiModelProperty(value = "")
  public List<String> getKeepTagAttributes() {
    return keepTagAttributes;
  }

  public void setKeepTagAttributes(List<String> keepTagAttributes) {
    this.keepTagAttributes = keepTagAttributes;
  }

  public HtmlSettings excludeTagAttributes(List<String> excludeTagAttributes) {
    this.excludeTagAttributes = excludeTagAttributes;
    return this;
  }

  public HtmlSettings addExcludeTagAttributesItem(String excludeTagAttributesItem) {
    if (this.excludeTagAttributes == null) {
      this.excludeTagAttributes = new ArrayList<String>();
    }
    this.excludeTagAttributes.add(excludeTagAttributesItem);
    return this;
  }

   /**
   * Get excludeTagAttributes
   * @return excludeTagAttributes
  **/
  @JsonProperty("exclude_tag_attributes")
  @ApiModelProperty(value = "")
  public List<String> getExcludeTagAttributes() {
    return excludeTagAttributes;
  }

  public void setExcludeTagAttributes(List<String> excludeTagAttributes) {
    this.excludeTagAttributes = excludeTagAttributes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HtmlSettings htmlSettings = (HtmlSettings) o;
    return Objects.equals(this.excludeTagsCompletely, htmlSettings.excludeTagsCompletely) &&
        Objects.equals(this.excludeTagsKeepContent, htmlSettings.excludeTagsKeepContent) &&
        Objects.equals(this.keepContent, htmlSettings.keepContent) &&
        Objects.equals(this.excludeContent, htmlSettings.excludeContent) &&
        Objects.equals(this.keepTagAttributes, htmlSettings.keepTagAttributes) &&
        Objects.equals(this.excludeTagAttributes, htmlSettings.excludeTagAttributes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(excludeTagsCompletely, excludeTagsKeepContent, keepContent, excludeContent, keepTagAttributes, excludeTagAttributes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HtmlSettings {\n");
    
    sb.append("    excludeTagsCompletely: ").append(toIndentedString(excludeTagsCompletely)).append("\n");
    sb.append("    excludeTagsKeepContent: ").append(toIndentedString(excludeTagsKeepContent)).append("\n");
    sb.append("    keepContent: ").append(toIndentedString(keepContent)).append("\n");
    sb.append("    excludeContent: ").append(toIndentedString(excludeContent)).append("\n");
    sb.append("    keepTagAttributes: ").append(toIndentedString(keepTagAttributes)).append("\n");
    sb.append("    excludeTagAttributes: ").append(toIndentedString(excludeTagAttributes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

