/*
 * Discovery
 * The IBM Watson&trade; Discovery Service is a cognitive search and content analytics engine that you can add to applications to identify patterns, trends and actionable insights to drive better decision-making. Securely unify structured and unstructured data with pre-enriched content, and use a simplified query language to eliminate the need for manual filtering of results. 
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.ibm.mfp.adapters.sample.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.ibm.mfp.adapters.sample.model.FontSettings;
import com.ibm.mfp.adapters.sample.model.WordStyles;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import javax.validation.constraints.*;

/**
 * WordHeadingDetection
 */
@javax.annotation.Generated(value = "com.github.mfpdev.adapters.swagger.codegen.MfpAdapterCodegen", date = "2017-05-19T15:47:02.385+05:30")
public class WordHeadingDetection   {
  @JsonProperty("fonts")
  private FontSettings fonts = null;

  @JsonProperty("styles")
  private WordStyles styles = null;

  public WordHeadingDetection fonts(FontSettings fonts) {
    this.fonts = fonts;
    return this;
  }

   /**
   * Get fonts
   * @return fonts
  **/
  @JsonProperty("fonts")
  @ApiModelProperty(value = "")

  public FontSettings getFonts() {
    return fonts;
  }

  public void setFonts(FontSettings fonts) {
    this.fonts = fonts;
  }

  public WordHeadingDetection styles(WordStyles styles) {
    this.styles = styles;
    return this;
  }

   /**
   * Get styles
   * @return styles
  **/
  @JsonProperty("styles")
  @ApiModelProperty(value = "")

  public WordStyles getStyles() {
    return styles;
  }

  public void setStyles(WordStyles styles) {
    this.styles = styles;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WordHeadingDetection wordHeadingDetection = (WordHeadingDetection) o;
    return Objects.equals(this.fonts, wordHeadingDetection.fonts) &&
        Objects.equals(this.styles, wordHeadingDetection.styles);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fonts, styles);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WordHeadingDetection {\n");
    
    sb.append("    fonts: ").append(toIndentedString(fonts)).append("\n");
    sb.append("    styles: ").append(toIndentedString(styles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
